name: Warm API (daily or manual)

on:
  workflow_dispatch:        # 允許你手動按掣觸發
  schedule:
    - cron: '0 2 * * *'     # 每日 UTC 02:00（香港上午10點）跑一次

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /api/warm
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://val-lab-api-one.vercel.app/api/warm
