name: Keep Warm
on:
  schedule:
    - cron: "0 */12 * * *"   # 每 12 小時 run 一次 (Hobby Plan 只支援 Daily)
jobs:
  warm:
    runs-on: ubuntu-latest
    steps:
      - name: Curl warm endpoint
        run: curl https://val-lab-api-one.vercel.app/api/warm
